// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AIChatRequest struct {
	Message   string `json:"message"`
	Context   string `json:"context,optional"`
	UserId    int64  `json:"user_id"`
	ChatType  string `json:"chat_type"` // "general", "resume", "job", "career"
	SessionId string `json:"session_id,optional"`
}

type AIChatResponse struct {
	ResponseId   int64        `json:"response_id"`
	Message      string       `json:"message"`
	ResponseType string       `json:"response_type"` // "text", "suggestion", "action"
	Suggestions  []string     `json:"suggestions,optional"`
	Actions      []ChatAction `json:"actions,optional"`
	SessionId    string       `json:"session_id"`
	Timestamp    int64        `json:"timestamp"`
}

type AIMatchRequest struct {
	ResumeId   int64                  `json:"resume_id"`
	JobId      int64                  `json:"job_id,optional"`
	MatchType  string                 `json:"match_type"` // "resume_job", "job_resume", "smart_recommend"
	Parameters map[string]interface{} `json:"parameters,optional"`
}

type AIMatchResponse struct {
	MatchId         int64            `json:"match_id"`
	MatchScore      float64          `json:"match_score"`
	MatchDetails    MatchDetails     `json:"match_details"`
	Recommendations []Recommendation `json:"recommendations"`
	Analysis        AnalysisResult   `json:"analysis"`
}

type AnalysisResult struct {
	Strengths   []string `json:"strengths"`
	Weaknesses  []string `json:"weaknesses"`
	Suggestions []string `json:"suggestions"`
	RiskFactors []string `json:"risk_factors"`
}

type ChatAction struct {
	ActionType  string                 `json:"action_type"` // "navigate", "create", "update", "search"
	ActionData  map[string]interface{} `json:"action_data"`
	Description string                 `json:"description"`
}

type EducationAnalysis struct {
	EducationLevel   string   `json:"education_level"`
	EducationQuality float64  `json:"education_quality"`
	Relevance        float64  `json:"relevance"`
	EducationGaps    []string `json:"education_gaps"`
}

type ExperienceAnalysis struct {
	TotalExperience    float64              `json:"total_experience"`
	RelevantExperience float64              `json:"relevant_experience"`
	ExperienceQuality  float64              `json:"experience_quality"`
	CareerProgression  string               `json:"career_progression"`
	IndustryExperience []IndustryExperience `json:"industry_experience"`
}

type IndustryExperience struct {
	Industry   string  `json:"industry"`
	Experience float64 `json:"experience"`
	Relevance  float64 `json:"relevance"`
}

type MatchDetails struct {
	SkillsMatch     float64 `json:"skills_match"`
	ExperienceMatch float64 `json:"experience_match"`
	EducationMatch  float64 `json:"education_match"`
	LocationMatch   float64 `json:"location_match"`
	SalaryMatch     float64 `json:"salary_match"`
	CultureMatch    float64 `json:"culture_match"`
}

type Recommendation struct {
	Type        string `json:"type"` // "skill", "experience", "education", "location"
	Title       string `json:"title"`
	Description string `json:"description"`
	Priority    int    `json:"priority"`
	Action      string `json:"action"`
}

type RecommendationItem struct {
	ItemId      int64                  `json:"item_id"`
	ItemType    string                 `json:"item_type"`
	Title       string                 `json:"title"`
	Description string                 `json:"description"`
	Score       float64                `json:"score"`
	Reasons     []string               `json:"reasons"`
	Metadata    map[string]interface{} `json:"metadata"`
}

type Response struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type ResumeAnalysisRequest struct {
	ResumeId     int64  `json:"resume_id"`
	AnalysisType string `json:"analysis_type"` // "comprehensive", "skills", "experience", "education"
	JobId        int64  `json:"job_id,optional"`
}

type ResumeAnalysisResponse struct {
	AnalysisId         int64              `json:"analysis_id"`
	ResumeId           int64              `json:"resume_id"`
	AnalysisType       string             `json:"analysis_type"`
	AnalysisResult     AnalysisResult     `json:"analysis_result"`
	SkillsAnalysis     SkillsAnalysis     `json:"skills_analysis"`
	ExperienceAnalysis ExperienceAnalysis `json:"experience_analysis"`
	EducationAnalysis  EducationAnalysis  `json:"education_analysis"`
	OverallScore       float64            `json:"overall_score"`
	CreateTime         int64              `json:"create_time"`
}

type SkillGap struct {
	SkillName     string  `json:"skill_name"`
	RequiredLevel string  `json:"required_level"`
	CurrentLevel  string  `json:"current_level"`
	GapScore      float64 `json:"gap_score"`
	Importance    string  `json:"importance"`
}

type SkillScore struct {
	SkillName  string  `json:"skill_name"`
	SkillLevel string  `json:"skill_level"`
	Score      float64 `json:"score"`
	Confidence float64 `json:"confidence"`
}

type SkillsAnalysis struct {
	TechnicalSkills      []SkillScore `json:"technical_skills"`
	SoftSkills           []SkillScore `json:"soft_skills"`
	SkillGaps            []SkillGap   `json:"skill_gaps"`
	SkillRecommendations []string     `json:"skill_recommendations"`
}

type SmartRecommendRequest struct {
	UserId        int64                  `json:"user_id"`
	RecommendType string                 `json:"recommend_type"` // "jobs", "resumes", "companies", "skills"
	Limit         int                    `json:"limit,default=10"`
	Filters       map[string]interface{} `json:"filters,optional"`
}

type SmartRecommendResponse struct {
	Recommendations []RecommendationItem `json:"recommendations"`
	Total           int                  `json:"total"`
	Algorithm       string               `json:"algorithm"`
	Confidence      float64              `json:"confidence"`
}
