// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token      string `json:"token"`
	UserId     int64  `json:"user_id"`
	Username   string `json:"username"`
	Role       string `json:"role"`
	ExpireTime int64  `json:"expire_time"`
}

type Permission struct {
	PermissionId   int64  `json:"permission_id"`
	PermissionName string `json:"permission_name"`
	PermissionCode string `json:"permission_code"`
	Resource       string `json:"resource"`
	Action         string `json:"action"`
}

type RefreshTokenRequest struct {
	Token string `json:"token"`
}

type RefreshTokenResponse struct {
	Token      string `json:"token"`
	ExpireTime int64  `json:"expire_time"`
}

type RegisterRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
	Phone    string `json:"phone"`
}

type RegisterResponse struct {
	UserId   int64  `json:"user_id"`
	Username string `json:"username"`
	Message  string `json:"message"`
}

type Response struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type Role struct {
	RoleId      int64        `json:"role_id"`
	RoleName    string       `json:"role_name"`
	RoleCode    string       `json:"role_code"`
	Description string       `json:"description"`
	Permissions []Permission `json:"permissions"`
}

type UserInfo struct {
	UserId     int64  `json:"user_id"`
	Username   string `json:"username"`
	Email      string `json:"email"`
	Phone      string `json:"phone"`
	Role       string `json:"role"`
	Status     int    `json:"status"`
	CreateTime int64  `json:"create_time"`
	UpdateTime int64  `json:"update_time"`
}
