// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	ai "ai/internal/handler/ai"
	"ai/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/ai/analysis/history/:userId",
					Handler: ai.GetAnalysisHistoryHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/ai/chat",
					Handler: ai.ChatHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/ai/chat/history/:sessionId",
					Handler: ai.GetChatHistoryHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/ai/health",
					Handler: ai.HealthCheckHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/ai/match",
					Handler: ai.MatchResumeJobHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/ai/match/history/:userId",
					Handler: ai.GetMatchHistoryHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/ai/recommend",
					Handler: ai.SmartRecommendHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/ai/resume/analyze",
					Handler: ai.AnalyzeResumeHandler(serverCtx),
				},
			}...,
		),
	)
}
