// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ChangePasswordRequest struct {
	OldPassword string `json:"old_password"`
	NewPassword string `json:"new_password"`
}

type Response struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type UpdateUserRequest struct {
	RealName string `json:"real_name,optional"`
	Avatar   string `json:"avatar,optional"`
	Gender   int    `json:"gender,optional"`
	Birthday string `json:"birthday,optional"`
	Location string `json:"location,optional"`
	Bio      string `json:"bio,optional"`
}

type User struct {
	UserId     int64  `json:"user_id"`
	Username   string `json:"username"`
	Email      string `json:"email"`
	Phone      string `json:"phone"`
	RealName   string `json:"real_name"`
	Avatar     string `json:"avatar"`
	Gender     int    `json:"gender"`
	Birthday   string `json:"birthday"`
	Location   string `json:"location"`
	Bio        string `json:"bio"`
	Status     int    `json:"status"`
	CreateTime int64  `json:"create_time"`
	UpdateTime int64  `json:"update_time"`
}

type UserListRequest struct {
	Page     int    `json:"page,default=1"`
	PageSize int    `json:"page_size,default=10"`
	Keyword  string `json:"keyword,optional"`
	Status   int    `json:"status,optional"`
}

type UserListResponse struct {
	List     []User `json:"list"`
	Total    int64  `json:"total"`
	Page     int    `json:"page"`
	PageSize int    `json:"page_size"`
}

type UserStats struct {
	TotalUsers        int64 `json:"total_users"`
	ActiveUsers       int64 `json:"active_users"`
	NewUsersToday     int64 `json:"new_users_today"`
	NewUsersThisMonth int64 `json:"new_users_this_month"`
}
