// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CreateJobRequest struct {
	CompanyId       int64    `json:"company_id"`
	JobTitle        string   `json:"job_title"`
	JobDescription  string   `json:"job_description"`
	JobRequirements string   `json:"job_requirements"`
	JobType         string   `json:"job_type"`
	WorkLocation    string   `json:"work_location"`
	SalaryMin       int      `json:"salary_min"`
	SalaryMax       int      `json:"salary_max"`
	Experience      string   `json:"experience"`
	Education       string   `json:"education"`
	Skills          []string `json:"skills"`
	Benefits        []string `json:"benefits"`
}

type Job struct {
	JobId           int64    `json:"job_id"`
	CompanyId       int64    `json:"company_id"`
	CompanyName     string   `json:"company_name"`
	JobTitle        string   `json:"job_title"`
	JobDescription  string   `json:"job_description"`
	JobRequirements string   `json:"job_requirements"`
	JobType         string   `json:"job_type"`
	WorkLocation    string   `json:"work_location"`
	SalaryMin       int      `json:"salary_min"`
	SalaryMax       int      `json:"salary_max"`
	Experience      string   `json:"experience"`
	Education       string   `json:"education"`
	Skills          []string `json:"skills"`
	Benefits        []string `json:"benefits"`
	Status          int      `json:"status"`
	CreateTime      int64    `json:"create_time"`
	UpdateTime      int64    `json:"update_time"`
}

type JobListRequest struct {
	Page      int   `json:"page,default=1"`
	PageSize  int   `json:"page_size,default=10"`
	CompanyId int64 `json:"company_id,optional"`
	Status    int   `json:"status,optional"`
}

type JobRecommendRequest struct {
	UserId int64 `json:"user_id"`
	Limit  int   `json:"limit,default=10"`
}

type JobRecommendResponse struct {
	List  []Job `json:"list"`
	Total int   `json:"total"`
}

type JobSearchRequest struct {
	Keyword    string   `json:"keyword,optional"`
	Location   string   `json:"location,optional"`
	JobType    string   `json:"job_type,optional"`
	SalaryMin  int      `json:"salary_min,optional"`
	SalaryMax  int      `json:"salary_max,optional"`
	Experience string   `json:"experience,optional"`
	Education  string   `json:"education,optional"`
	Skills     []string `json:"skills,optional"`
	Page       int      `json:"page,default=1"`
	PageSize   int      `json:"page_size,default=10"`
}

type JobSearchResponse struct {
	List     []Job `json:"list"`
	Total    int64 `json:"total"`
	Page     int   `json:"page"`
	PageSize int   `json:"page_size"`
}

type Response struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type UpdateJobRequest struct {
	JobTitle        string   `json:"job_title,optional"`
	JobDescription  string   `json:"job_description,optional"`
	JobRequirements string   `json:"job_requirements,optional"`
	JobType         string   `json:"job_type,optional"`
	WorkLocation    string   `json:"work_location,optional"`
	SalaryMin       int      `json:"salary_min,optional"`
	SalaryMax       int      `json:"salary_max,optional"`
	Experience      string   `json:"experience,optional"`
	Education       string   `json:"education,optional"`
	Skills          []string `json:"skills,optional"`
	Benefits        []string `json:"benefits,optional"`
	Status          int      `json:"status,optional"`
}
