// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	blockchain "blockchain/internal/handler/blockchain"
	"blockchain/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/blockchain/block/:blockHeight",
					Handler: blockchain.GetBlockInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/blockchain/health",
					Handler: blockchain.GetBlockchainHealthHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/blockchain/permission/change",
					Handler: blockchain.RecordPermissionChangeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/blockchain/stats",
					Handler: blockchain.GetBlockchainStatsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/blockchain/transaction",
					Handler: blockchain.RecordTransactionHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/blockchain/transaction/:transactionId",
					Handler: blockchain.GetTransactionByIdHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/blockchain/transaction/hash/:transactionHash",
					Handler: blockchain.GetTransactionByHashHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/blockchain/transaction/history",
					Handler: blockchain.QueryTransactionHistoryHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/blockchain/validate",
					Handler: blockchain.ValidateDataConsistencyHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/blockchain/version/status",
					Handler: blockchain.RecordVersionStatusChangeHandler(serverCtx),
				},
			}...,
		),
	)
}
