// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AnalyzeResumeRequest struct {
	ResumeId int64 `json:"resume_id"`
	JobId    int64 `json:"job_id,optional"`
}

type AnalyzeResumeResponse struct {
	MatchScore    float64  `json:"match_score"`
	Strengths     []string `json:"strengths"`
	Weaknesses    []string `json:"weaknesses"`
	Suggestions   []string `json:"suggestions"`
	SkillsMatch   []string `json:"skills_match"`
	SkillsMissing []string `json:"skills_missing"`
}

type Certificate struct {
	CertificateId       int64  `json:"certificate_id"`
	CertificateName     string `json:"certificate_name"`
	IssuingOrganization string `json:"issuing_organization"`
	IssueDate           string `json:"issue_date"`
	ExpiryDate          string `json:"expiry_date"`
	CertificateUrl      string `json:"certificate_url"`
}

type CreateResumeRequest struct {
	ResumeName     string           `json:"resume_name"`
	PersonalInfo   PersonalInfo     `json:"personal_info"`
	WorkExperience []WorkExperience `json:"work_experience"`
	Education      []Education      `json:"education"`
	Skills         []Skill          `json:"skills"`
	Projects       []Project        `json:"projects"`
	Certificates   []Certificate    `json:"certificates"`
}

type Education struct {
	EducationId int64  `json:"education_id"`
	SchoolName  string `json:"school_name"`
	Major       string `json:"major"`
	Degree      string `json:"degree"`
	StartDate   string `json:"start_date"`
	EndDate     string `json:"end_date"`
	Description string `json:"description"`
}

type MatchDetails struct {
	SkillsMatch     float64 `json:"skills_match"`
	ExperienceMatch float64 `json:"experience_match"`
	EducationMatch  float64 `json:"education_match"`
	LocationMatch   float64 `json:"location_match"`
	SalaryMatch     float64 `json:"salary_match"`
}

type MatchResumeRequest struct {
	ResumeId int64 `json:"resume_id"`
	JobId    int64 `json:"job_id"`
}

type MatchResumeResponse struct {
	MatchScore   float64      `json:"match_score"`
	MatchDetails MatchDetails `json:"match_details"`
}

type PersonalInfo struct {
	RealName string `json:"real_name"`
	Email    string `json:"email"`
	Phone    string `json:"phone"`
	Gender   int    `json:"gender"`
	Birthday string `json:"birthday"`
	Location string `json:"location"`
	Bio      string `json:"bio"`
	Avatar   string `json:"avatar"`
}

type Project struct {
	ProjectId          int64    `json:"project_id"`
	ProjectName        string   `json:"project_name"`
	ProjectDescription string   `json:"project_description"`
	StartDate          string   `json:"start_date"`
	EndDate            string   `json:"end_date"`
	Technologies       []string `json:"technologies"`
	Responsibilities   []string `json:"responsibilities"`
}

type Response struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type Resume struct {
	ResumeId       int64            `json:"resume_id"`
	UserId         int64            `json:"user_id"`
	ResumeName     string           `json:"resume_name"`
	PersonalInfo   PersonalInfo     `json:"personal_info"`
	WorkExperience []WorkExperience `json:"work_experience"`
	Education      []Education      `json:"education"`
	Skills         []Skill          `json:"skills"`
	Projects       []Project        `json:"projects"`
	Certificates   []Certificate    `json:"certificates"`
	Status         int              `json:"status"`
	CreateTime     int64            `json:"create_time"`
	UpdateTime     int64            `json:"update_time"`
}

type Skill struct {
	SkillId    int64  `json:"skill_id"`
	SkillName  string `json:"skill_name"`
	SkillLevel string `json:"skill_level"`
	Category   string `json:"category"`
}

type UpdateResumeRequest struct {
	ResumeName     string           `json:"resume_name,optional"`
	PersonalInfo   PersonalInfo     `json:"personal_info,optional"`
	WorkExperience []WorkExperience `json:"work_experience,optional"`
	Education      []Education      `json:"education,optional"`
	Skills         []Skill          `json:"skills,optional"`
	Projects       []Project        `json:"projects,optional"`
	Certificates   []Certificate    `json:"certificates,optional"`
	Status         int              `json:"status,optional"`
}

type WorkExperience struct {
	ExperienceId int64    `json:"experience_id"`
	CompanyName  string   `json:"company_name"`
	Position     string   `json:"position"`
	StartDate    string   `json:"start_date"`
	EndDate      string   `json:"end_date"`
	Description  string   `json:"description"`
	Achievements []string `json:"achievements"`
}
