// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	resume "resume/internal/handler/resume"
	"resume/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/resume",
					Handler: resume.CreateResumeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/resume/:id",
					Handler: resume.GetResumeHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/resume/:id",
					Handler: resume.UpdateResumeHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/resume/:id",
					Handler: resume.DeleteResumeHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/resume/analyze",
					Handler: resume.AnalyzeResumeHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/resume/match",
					Handler: resume.MatchResumeHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/resume/parse",
					Handler: resume.ParseResumeFileHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/resume/upload",
					Handler: resume.UploadResumeFileHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/resume/user/:userId",
					Handler: resume.GetUserResumesHandler(serverCtx),
				},
			}...,
		),
	)
}
