// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	auth "auth/internal/handler/auth"
	"auth/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/auth/login",
					Handler: auth.LoginHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/auth/logout",
					Handler: auth.LogoutHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/auth/refresh",
					Handler: auth.RefreshHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/auth/register",
					Handler: auth.RegisterHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/auth/user/info",
					Handler: auth.UserInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/auth/user/permissions",
					Handler: auth.PermissionsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/auth/user/roles",
					Handler: auth.RolesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/auth/validate",
					Handler: auth.ValidateTokenHandler(serverCtx),
				},
			}...,
		),
	)
}
