// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type BlockchainHealth struct {
	Status              string  `json:"status"` // "healthy", "degraded", "unhealthy"
	LastBlockHeight     int64   `json:"last_block_height"`
	LastBlockTime       int64   `json:"last_block_time"`
	PendingTransactions int64   `json:"pending_transactions"`
	NetworkLatency      float64 `json:"network_latency"`
	ErrorRate           float64 `json:"error_rate"`
	Uptime              float64 `json:"uptime"`
}

type BlockchainStats struct {
	TotalTransactions     int64   `json:"total_transactions"`
	TotalBlocks           int64   `json:"total_blocks"`
	ActiveTransactions    int64   `json:"active_transactions"`
	PendingTransactions   int64   `json:"pending_transactions"`
	ConfirmedTransactions int64   `json:"confirmed_transactions"`
	FailedTransactions    int64   `json:"failed_transactions"`
	AverageBlockTime      float64 `json:"average_block_time"`
	NetworkHashRate       float64 `json:"network_hash_rate"`
}

type BlockchainTransaction struct {
	TransactionId   string `json:"transaction_id"`
	TransactionType string `json:"transaction_type"`
	EntityId        string `json:"entity_id"`
	VersionSource   string `json:"version_source"`
	OldValue        string `json:"old_value"`
	NewValue        string `json:"new_value"`
	ChangeReason    string `json:"change_reason"`
	OperatorId      string `json:"operator_id"`
	TransactionHash string `json:"transaction_hash"`
	TransactionData string `json:"transaction_data"`
	Status          string `json:"status"`
	BlockHeight     int64  `json:"block_height"`
	CreateTime      int64  `json:"create_time"`
	ConfirmTime     int64  `json:"confirm_time"`
}

type DataConsistencyValidateRequest struct {
	EntityId      string `json:"entity_id"`
	EntityType    string `json:"entity_type"`
	VersionSource string `json:"version_source"`
	ValidateType  string `json:"validate_type"` // "full", "incremental", "specific"
}

type DataConsistencyValidateResponse struct {
	ValidationId     string          `json:"validation_id"`
	EntityId         string          `json:"entity_id"`
	EntityType       string          `json:"entity_type"`
	ValidationResult string          `json:"validation_result"` // "consistent", "inconsistent", "error"
	Inconsistencies  []Inconsistency `json:"inconsistencies"`
	ValidationTime   int64           `json:"validation_time"`
}

type Inconsistency struct {
	Field           string `json:"field"`
	BlockchainValue string `json:"blockchain_value"`
	DatabaseValue   string `json:"database_value"`
	TransactionHash string `json:"transaction_hash"`
	BlockHeight     int64  `json:"block_height"`
}

type PermissionChangeRequest struct {
	UserId        string `json:"user_id"`
	VersionSource string `json:"version_source"`
	OldPermission string `json:"old_permission"`
	NewPermission string `json:"new_permission"`
	ChangeReason  string `json:"change_reason"`
	OperatorId    string `json:"operator_id"`
}

type PermissionChangeResponse struct {
	TransactionId   string `json:"transaction_id"`
	TransactionHash string `json:"transaction_hash"`
	BlockHeight     int64  `json:"block_height"`
	Status          string `json:"status"`
	CreateTime      int64  `json:"create_time"`
}

type QueryTransactionHistoryRequest struct {
	EntityId        string `json:"entity_id,optional"`
	TransactionType string `json:"transaction_type,optional"`
	VersionSource   string `json:"version_source,optional"`
	StartTime       int64  `json:"start_time,optional"`
	EndTime         int64  `json:"end_time,optional"`
	Page            int    `json:"page,default=1"`
	PageSize        int    `json:"page_size,default=10"`
}

type QueryTransactionHistoryResponse struct {
	Transactions []BlockchainTransaction `json:"transactions"`
	Total        int64                   `json:"total"`
	Page         int                     `json:"page"`
	PageSize     int                     `json:"page_size"`
}

type RecordTransactionRequest struct {
	TransactionType string                 `json:"transaction_type"`
	EntityId        string                 `json:"entity_id"`
	VersionSource   string                 `json:"version_source"`
	OldValue        string                 `json:"old_value"`
	NewValue        string                 `json:"new_value"`
	ChangeReason    string                 `json:"change_reason"`
	OperatorId      string                 `json:"operator_id"`
	TransactionData map[string]interface{} `json:"transaction_data,optional"`
}

type RecordTransactionResponse struct {
	TransactionId   string `json:"transaction_id"`
	TransactionHash string `json:"transaction_hash"`
	BlockHeight     int64  `json:"block_height"`
	Status          string `json:"status"`
	CreateTime      int64  `json:"create_time"`
}

type Response struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type VersionStatusChangeRequest struct {
	UserId        string `json:"user_id"`
	VersionSource string `json:"version_source"`
	OldStatus     string `json:"old_status"`
	NewStatus     string `json:"new_status"`
	ChangeReason  string `json:"change_reason"`
	OperatorId    string `json:"operator_id"`
}

type VersionStatusChangeResponse struct {
	TransactionId   string `json:"transaction_id"`
	TransactionHash string `json:"transaction_hash"`
	BlockHeight     int64  `json:"block_height"`
	Status          string `json:"status"`
	CreateTime      int64  `json:"create_time"`
}
