// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	company "company/internal/handler/company"
	"company/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/company",
					Handler: company.CreateCompanyHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/company/:id",
					Handler: company.GetCompanyHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/company/:id",
					Handler: company.UpdateCompanyHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/company/:id",
					Handler: company.DeleteCompanyHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/company/list",
					Handler: company.GetCompanyListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/company/logo",
					Handler: company.UploadCompanyLogoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/company/search",
					Handler: company.SearchCompaniesHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/company/stats",
					Handler: company.GetCompanyStatsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/company/verify",
					Handler: company.VerifyCompanyHandler(serverCtx),
				},
			}...,
		),
	)
}
