// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type Company struct {
	CompanyId          int64  `json:"company_id"`
	CompanyName        string `json:"company_name"`
	CompanyLogo        string `json:"company_logo"`
	CompanyDescription string `json:"company_description"`
	Industry           string `json:"industry"`
	CompanySize        string `json:"company_size"`
	Website            string `json:"website"`
	Address            string `json:"address"`
	City               string `json:"city"`
	Province           string `json:"province"`
	Country            string `json:"country"`
	ContactPerson      string `json:"contact_person"`
	ContactPhone       string `json:"contact_phone"`
	ContactEmail       string `json:"contact_email"`
	Status             int    `json:"status"`
	VerificationStatus int    `json:"verification_status"`
	CreateTime         int64  `json:"create_time"`
	UpdateTime         int64  `json:"update_time"`
}

type CompanySearchRequest struct {
	Keyword     string `json:"keyword,optional"`
	Industry    string `json:"industry,optional"`
	CompanySize string `json:"company_size,optional"`
	City        string `json:"city,optional"`
	Province    string `json:"province,optional"`
	Status      int    `json:"status,optional"`
	Page        int    `json:"page,default=1"`
	PageSize    int    `json:"page_size,default=10"`
}

type CompanySearchResponse struct {
	List     []Company `json:"list"`
	Total    int64     `json:"total"`
	Page     int       `json:"page"`
	PageSize int       `json:"page_size"`
}

type CompanyStats struct {
	TotalCompanies        int64 `json:"total_companies"`
	VerifiedCompanies     int64 `json:"verified_companies"`
	ActiveCompanies       int64 `json:"active_companies"`
	NewCompaniesToday     int64 `json:"new_companies_today"`
	NewCompaniesThisMonth int64 `json:"new_companies_this_month"`
}

type CompanyVerificationRequest struct {
	CompanyId             int64    `json:"company_id"`
	BusinessLicense       string   `json:"business_license"`
	TaxNumber             string   `json:"tax_number"`
	LegalPerson           string   `json:"legal_person"`
	LegalPersonId         string   `json:"legal_person_id"`
	VerificationDocuments []string `json:"verification_documents"`
}

type CompanyVerificationResponse struct {
	VerificationId int64  `json:"verification_id"`
	Status         string `json:"status"`
	Message        string `json:"message"`
	SubmitTime     int64  `json:"submit_time"`
}

type CreateCompanyRequest struct {
	CompanyName        string `json:"company_name"`
	CompanyLogo        string `json:"company_logo,optional"`
	CompanyDescription string `json:"company_description,optional"`
	Industry           string `json:"industry"`
	CompanySize        string `json:"company_size"`
	Website            string `json:"website,optional"`
	Address            string `json:"address"`
	City               string `json:"city"`
	Province           string `json:"province"`
	Country            string `json:"country"`
	ContactPerson      string `json:"contact_person"`
	ContactPhone       string `json:"contact_phone"`
	ContactEmail       string `json:"contact_email"`
}

type Response struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type UpdateCompanyRequest struct {
	CompanyName        string `json:"company_name,optional"`
	CompanyLogo        string `json:"company_logo,optional"`
	CompanyDescription string `json:"company_description,optional"`
	Industry           string `json:"industry,optional"`
	CompanySize        string `json:"company_size,optional"`
	Website            string `json:"website,optional"`
	Address            string `json:"address,optional"`
	City               string `json:"city,optional"`
	Province           string `json:"province,optional"`
	Country            string `json:"country,optional"`
	ContactPerson      string `json:"contact_person,optional"`
	ContactPhone       string `json:"contact_phone,optional"`
	ContactEmail       string `json:"contact_email,optional"`
	Status             int    `json:"status,optional"`
}
