// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	job "job/internal/handler/job"
	"job/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/job",
					Handler: job.CreateJobHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/job/:id",
					Handler: job.GetJobHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/job/:id",
					Handler: job.UpdateJobHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/job/:id",
					Handler: job.DeleteJobHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/job/company/:companyId",
					Handler: job.GetCompanyJobsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/job/list",
					Handler: job.GetJobListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/job/recommend",
					Handler: job.RecommendJobsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/job/search",
					Handler: job.SearchJobsHandler(serverCtx),
				},
			}...,
		),
	)
}
